# Generated by Django 4.2.11 on 2024-03-21 21:56

from django.db import migrations
from shortener.models import Counter


def create_url_counter(apps, schema_editor):
    counter = Counter(name='url_counter')
    counter.save()

class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_url_counter, lambda *args, **kwargs: None),
    ]
