# Generated by Django 4.2.11 on 2024-03-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_url_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
